import "dotenv/config";

export const ENV = {
  GROQ_API_KEY: process.env.GROQ_API_KEY!,
  TAVILY_API_KEY: process.env.WEB_SEARCH_API!,
  OPENROUTER_API_KEY: process.env.OPENROUTER_API_KEY!,
  GOOGLE_API_KEY: process.env.GOOGLE_API_KEY!,
  GMAIL_USER: process.env.NODEMAILER_USER!,
  GMAIL_APP_PASSWORD: process.env.NODEMAILER_APP_PASSWORD!,
  GOOGLE_CALENDAR_CLIENT_ID: process.env.GOOGLE_CALENDAR_CLIENT_ID!,
  GOOGLE_CALENDAR_CLIENT_SECRET: process.env.GOOGLE_CALENDAR_CLIENT_SECRET!,
};
